---
abstract: "Your personal twitter b........ lalalalalala\r"
author:
  - "Torsten Raudssus <torsten@raudssus.de> L<http://www.raudssus.de/>\r"
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Twitch
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  IO::All: 0
  JSON: 0
  Moose: 1.15
  MooseX::Getopt: 0
  MooseX::LogDispatch: 0
  MooseX::POE: 0.208
  Net::Twitter: 0
  POE: 0
  POE::Component::RSSAggregator: 0
  String::Truncate: 0
  Text::Trim: 0
  URI: 0
  WWW::Shorten: 0
  WWW::Shorten::Bitly: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
